# DataFrame과 리스트, 딕셔너리, ndarray 상호변환

## 1. 1차원 데이터를 DataFrame으로 변환

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [5]:
# 1차원 리스트 생성
col_name = ['col_1']
list1 = [1, 2, 3]
print(type(list1), list1)

<class 'list'> [1, 2, 3]

In [6]:
# ndarray로 변환
array1 = np.array(list1)
print(type(array1), array1)

<class 'numpy.ndarray'> [1 2 3]

In [12]:
# list1, array1를 DataFrame으로 생성(변환)
df_1 = pd.DataFrame(list1, columns = col_name, index = ['a', 'b', 'c'])
df_2 = pd.DataFrame(array1, columns = col_name)
print(df_1)
print('-' * 30)
print(df_2)

   col_1
a      1
b      2
c      3
------------------------------
   col_1
0      1
1      2
2      3

##  2. 2차원 데이터를 DataFrame으로 변환

In [13]:
# 컬럼명 생성
col_names = ['col1', 'col2', 'col3']
col_names

['col1', 'col2', 'col3']

In [14]:
# 2차원 리스트 생성
list2 = [[1, 2, 3],
         [4, 5, 6]]
list2

[[1, 2, 3], [4, 5, 6]]

In [16]:
# list2를 ndarray로 변환
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# list2, array2를 DataFrame으로 변환
df2_1 = pd.DataFrame(list2, columns = col_names)
df2_2 = pd.DataFrame(array2, columns = col_names)

display(df2_1)
print('-' * 30)
display(df2_2)

   col1  col2  col3
0     1     2     3
1     4     5     6

------------------------------

   col1  col2  col3
0     1     2     3
1     4     5     6

## 3. 딕셔너리를 DataFrame으로 변환

In [23]:
# 딕셔너리 생성
dict1 = {
    'col1' : [1, 2, 3],
    'col2' : [4, 5, 6],
    'col3' : [7, 8, 9]
}

dict1

{'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}

In [24]:
# DataFrame 생성
df_dict1 = pd.DataFrame(dict1)
df_dict1

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

## 4. DataFrame을 ndarray, list, dictionary로 변환

In [27]:
# df_dict1 데이터프레임을 ndarray로 변환
array3 = df_dict1.values
print(type(array3), array3, sep = '\n')

<class 'numpy.ndarray'>
[[1 4 7]
 [2 5 8]
 [3 6 9]]

In [28]:
# df_dict1 데이터프레임을 list로 변환
list3 = df_dict1.values.tolist()
print(type(list3), list3, sep = '\n')

<class 'list'>
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [29]:
# df_dict1 데이터프레임을 dictionary로 변환
dict3 = df_dict1.to_dict()
dict3

{'col1': {0: 1, 1: 2, 2: 3},
 'col2': {0: 4, 1: 5, 2: 6},
 'col3': {0: 7, 1: 8, 2: 9}}

## 5. shape 속성 정리
- python List :
- python Dictionary :
- Numpy ndarray :
- Pandas DataFrame :
- Pandas Series :

In [34]:
# list 생성
print(type(list1), list1, sep = '\n')
list.shape                     # type object 'list' has no attribute 'shape'

<class 'list'>
[1, 2, 3]

AttributeError: type object 'list' has no attribute 'shape'

In [36]:
# dictionary 생성
print(type(dict1), dict1, sep = '\n')
dict1.shape                     # 'dict' object has no attribute 'shape'

<class 'dict'>
{'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}

AttributeError: 'dict' object has no attribute 'shape'

In [38]:
# array
print(type(array1), array1, sep = '\n')
array1.shape

<class 'numpy.ndarray'>
[1 2 3]

(3,)

In [38]:
# array
print(type(array1), array1, sep = '\n')
array1.shape

<class 'numpy.ndarray'>
[1 2 3]

(3,)

In [40]:
# DataFrame
print(type(df_1), df_1, sep = '\n')
df_1.shape

<class 'pandas.core.frame.DataFrame'>
   col_1
a      1
b      2
c      3

(3, 1)

In [42]:
# Series
series1 = pd.Series([1, 2, 3])
print(type(series1), series1, sep = '\n')
series1.shape

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
dtype: int64

(3,)

## 6. DataFrame