# DataFrame Query, Merge

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [2]:
# Titanic 데이터셋 로드
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 1. Query를 이용한 데이터 조회
- query() : 조건식을 문자열 형식으로 작성하여 조회

In [4]:
# exam.csv 데이터 로드
exam_df = pd.read_csv('data/exam.csv')
exam_df.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [8]:
# exam_df의 형태, 정보 확인
print(f"shape : {exam_df.shape}, info : {exam_df.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes
shape : (20, 5), info : None

In [9]:
# 수학 점수가 70점 이상인 데이터 조회
exam_df.query('math >= 70')

    id  nclass  math  english  science
6    7       2    80       90       45
7    8       2    90       78       25
14  15       4    75       56       78
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [14]:
# 수학 점수가 70점 이상인 2반 학생들 데이터 조회
# 두 개 이상의 조건은 And(&), OR(|) 연산 적용
query_exp = '(math >= 70) & (nclass == 2)'
exam_df.query(query_exp)

   id  nclass  math  english  science
6   7       2    80       90       45
7   8       2    90       78       25

In [16]:
# 1반 이거나 영어 점수가 90점 이상인 데이터 조회
query_exp = 'nclass == 1 | english >= 90'
exam_df.query(query_exp)

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
6    7       2    80       90       45
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65

In [27]:
# nclass 기준 groupby
exam_df.groupby(by = 'nclass').count()

# 1, 3, 5반 데이터만 조회
query_exp = 'nclass == 1 | nclass == 3 | nclass == 5'
exam_df.query(query_exp)
query_exp2 = 'nclass in (1, 3, 5)'
exam_df.query(query_exp2)

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [32]:
# 1반의 수학, 과학 점수 평균 구하기
query_exp = 'nclass == 1'
exam_df.query(query_exp)[['math', 'science']].mean()

math       46.25
science    61.50
dtype: float64

In [39]:
# 변수를 이용하여 query 조건 생성
nclass_input = int(input())
query_exp = 'nclass == @nclass_input'
exam_df.query(query_exp)

 1

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

- 타이타닉 데이터셋 쿼리 실습

In [41]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [42]:
# 1등급 객실의 승객 정보 조회 - Boolean Indexing
titanic_df[titanic_df['Pclass'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [46]:
# 1등급 객실의 승객 정보 조회 - query 사용
query_exp = 'Pclass == 1'
titanic_df.query(query_exp)['PassengerId'].count()

np.int64(216)

In [52]:
# 생존한 여성 승객 조회
query_exp = "(Survived == 1) & (Sex == 'female')"
titanic_df.query(query_exp)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [57]:
# Boolean indexing ver.
titanic_df[(titanic_df['Survived'] ==1) & (titanic_df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [64]:
# S, Q 항구에서 탑승한 승객 중 생존자 조회
titanic_df[(titanic_df['Embarked'].isin(['S', 'Q'])) & (titanic_df['Survived'] == 1)].groupby(by = 'Embarked').count()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Embarked,,,,,,,,,,,
Q,30,30,30,30,30,8,30,30,30,30,2
S,217,217,217,217,217,201,217,217,217,217,80

In [67]:
# query ver.
query_exp = 'Embarked in ("S", "Q") & Survived == 1'
titanic_df.query(query_exp).groupby(by = 'Embarked')['PassengerId'].count()

Embarked
Q     30
S    217
Name: PassengerId, dtype: int64

In [75]:
# query() 함수의 메서드 체이닝
# 1, 2 객실 등급의 남자 승객 조회

titanic_df.query('Pclass in (1, 2)').query('Sex == "male"').groupby(by = 'Pclass').nunique()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,122,2,122,1,49,4,4,114,70,87,3
2,108,2,108,1,44,3,3,94,31,4,3

## 2. Merge
- SQL의 조인과 유사함
- inner join
- left join
- right join
- full outer join

### (1) Inner Join
- key를 기준으로 두 개의 데이터프레임(테이블)
- 예제) '이름'을 키로하여 Inner Join(교집합) 수행

In [76]:
df1 = pd.DataFrame(
    {
        '이름' : ['홍길동', '이순신', '김유신'],
        '키' : [180, 170, 175]
    }
)
df1

    이름    키
0  홍길동  180
1  이순신  170
2  김유신  175

In [77]:
df2 = pd.DataFrame(
    {
        '이름' : ['홍길동', '이순신', '김영희'],
        '성별' : ['남자', '남자', '여자']
    }
)
df2

    이름  성별
0  홍길동  남자
1  이순신  남자
2  김영희  여자

In [80]:
# Inner Join, how = 'inner' 기본값, 생략 가능
pd.merge(df1, df2, how = 'inner')

    이름    키  성별
0  홍길동  180  남자
1  이순신  170  남자

### (2) Left Outer Join
- 왼쪽 데이터셋에 있는 데이터프레임(테이블)의 키를 기준으로 병합

In [81]:
# df1, df2 데이터프레임 Left Outer Join(Inner Join + Left 테이블 모든 데이터셋)
pd.merge(df1, df2, how = 'left')

    이름    키   성별
0  홍길동  180   남자
1  이순신  170   남자
2  김유신  175  NaN

### (3) Right Outer Join
- 오른쪽 데이터프레임에 있는 모든 데이터를 병합

In [82]:
# df1, df2 데이터프레임 Right Outer Join(Inner Join + Right 테이블 모든 데이터셋)
pd.merge(df1, df2, how = 'right')

    이름      키  성별
0  홍길동  180.0  남자
1  이순신  170.0  남자
2  김영희    NaN  여자

### (4) Full Outer Join
- 키를 기준으로 두 데이터프레임에 존재하는 모든 데이터를 기준으로 병합

In [85]:
# df1, df2 데이터프레임 Full Outer Join
pd.merge(df1, df2, how = 'outer')

    이름      키   성별
0  김영희    NaN   여자
1  김유신  175.0  NaN
2  이순신  170.0   남자
3  홍길동  180.0   남자

## 3. Concat 함수를 이용한 데이터 병합

In [86]:
# df1, df2를 행 기준으로 concat
pd.concat([df1, df2])

    이름      키   성별
0  홍길동  180.0  NaN
1  이순신  170.0  NaN
2  김유신  175.0  NaN
0  홍길동    NaN   남자
1  이순신    NaN   남자
2  김영희    NaN   여자

In [88]:
# df1, df2를 열 기준으로 concat
pd.concat([df1, df2], axis = 1)

    이름    키   이름  성별
0  홍길동  180  홍길동  남자
1  이순신  170  이순신  남자
2  김유신  175  김영희  여자